DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS summary;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE summary(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id integer NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passage TEXT NOT NULL,
    summary_text TEXT NOT NULL
);